### ISSUE TITLE
Device Group issues when enabled

### ISSUE THREAD

**Issue by ferbulous** [openshwprojects/OpenBK7231T_App#321] opened 2022-10-22 19:06 UTC
Tested with the following devices:
a. Tasmota E27 Led
b. Openbkt E27 Led (N device). I'm not sure if it's device related since I only have N now.

Enabled:
1) Toggle on/off works but not for brightness & color change (done directly on the openbk ui). On homeassistant dashboard, i could toggle from the tasmota device but if I did the same for openbk issue (3) occurs
2) Sometimes repeated group command occurs (e.g keeps toggling on/off for 2-4 secs before it stops)
3) Openbk crashes when sending mqtt payload from homeassistant. Had to power cycle again when this happens

More info in this video:

https://youtu.be/ju0Mn1QNq1I

**Comment by openshwprojects** [comment] 2022-10-23 04:29
Today I have increased some stack sizes, can you recheck?

Regarding MQTT crash - @valeklubomir , ideas?

Regarding "blinking" - it might be because current DGR does not ack, but when I tested it, it was stable. Might improve it soon.

**Comment by ferbulous** [comment] 2022-10-23 08:21
Hi, 
Issue 2 is  still there
Issue 3 - I can send mqtt payload the first time, openbk does receive it and then it crashes

https://youtu.be/btTxuRLcuPw

Some of the logs during testing:
``
Info:DGR:DGR_Parse: [192.168.1.185] seq 13824, flags 2049
Info:MQTT:MQTT deduper sent 55, culled 260
Info:MAIN:Time 143, free 80496, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.185] seq 3584, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 18176, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 18432, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 18176, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 18432, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 18944, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 18944, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 19200, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 19200, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 3840, flags 0
Info:MQTT:MQTT deduper sent 58, culled 279
Info:MAIN:Time 152, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 19456, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 19712, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 19456, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 19712, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 20480, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 20736, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 20480, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 20736, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 20992, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 21248, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 20992, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 21248, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 3840, flags 0
Info:MQTT:MQTT deduper sent 58, culled 288
Info:MAIN:Time 153, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 22272, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 22528, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 22784, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 22272, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 22528, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 22784, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 23040, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 23296, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 23552, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 23040, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 23296, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 23552, flags 2049
Info:MQTT:MQTT deduper sent 58, culled 297
Info:MAIN:Time 154, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 23808, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 24064, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 24320, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 23808, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 24064, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 24320, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 3840, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 25600, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 25856, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 26112, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 25600, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 25856, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 26112, flags 2049
Info:MQTT:MQTT deduper sent 58, culled 307
Info:MAIN:Time 155, free 81352, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 26624, flags 1
Info:MQTT:Publishing val 0 to smartrul_bulb1/led_enableAll/get retain=1
Info:MQTT:MQTT deduper sent 59, culled 307
Info:MAIN:Time 156, free 80504, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.185] seq 26624, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 3840, flags 0
Info:MQTT:MQTT deduper sent 59, culled 309
Info:MAIN:Time 160, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:GEN:dhcp=0 ip=192.168.1.109 gate=192.168.1.1 mask=255.255.255.0 mac=d8:1f:12:aa:1e:0b 
Info:DGR:DGR_Parse: [192.168.1.185] seq 4096, flags 0
Info:MQTT:Publishing val 1 to smartrul_bulb1/led_enableAll/get retain=1
Info:DGR:DGR_Parse: [192.168.1.185] seq 4096, flags 0
Info:DGR:DGR_Parse: [192.168.1.185] seq 4096, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 27904, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 28160, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 28416, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 27904, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 28160, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 28416, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4096, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 28672, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 29184, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 29440, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 28672, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 29184, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 29440, flags 2049
Info:MQTT:MQTT deduper sent 60, culled 318
Info:MAIN:Time 161, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 30464, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 30720, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 30976, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 31232, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 30464, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 30720, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4096, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 31488, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 31744, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 32000, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 32256, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 31488, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 31744, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 32000, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 32256, flags 2049
Info:MQTT:MQTT deduper sent 60, culled 331
Info:MAIN:Time 162, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 32512, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 32768, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 33024, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 33280, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 33536, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 32512, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 32768, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 33280, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 33024, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 33536, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 35072, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 35328, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 35584, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 35840, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 36096, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 35072, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 35328, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 35584, flags 2049
Info:MQTT:MQTT deduper sent 60, culled 346
Info:MAIN:Time 163, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 36352, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 36608, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 36864, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 37120, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 37376, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 36352, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 36608, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 36864, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4096, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 39168, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 39424, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 39680, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 39168, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 39424, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 39680, flags 2049
Info:MQTT:MQTT deduper sent 60, culled 360
Info:MAIN:Time 164, free 81344, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 40448, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 40704, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 40960, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 40704, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 40960, flags 2049
Info:MQTT:MQTT deduper sent 60, culled 363
Info:MAIN:Time 165, free 80048, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:MQTT:Publishing val 0 to smartrul_bulb1/led_enableAll/get retain=1
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:MQTT:MQTT deduper sent 61, culled 365
Info:MAIN:Time 166, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 42240, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 42496, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 42240, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 42496, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 43264, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 43520, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 43776, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 43264, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 43520, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 43776, flags 2049
Info:MQTT:MQTT deduper sent 61, culled 373
Info:MAIN:Time 167, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 44032, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 44288, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 44544, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 44032, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 44288, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 44544, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 44800, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 45056, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 45312, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 45568, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 44800, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 45056, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 45312, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 45824, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 46336, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 46592, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 45824, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 46336, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 46592, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:MQTT:MQTT deduper sent 61, culled 385
Info:MAIN:Time 168, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 47104, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 47360, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 47616, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 47104, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 47360, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 47616, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 48128, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 48384, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 48128, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 48384, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 48640, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 48896, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 48640, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 48896, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 49152, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 49408, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 49664, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 49152, flags 2049
Info:MQTT:MQTT deduper sent 61, culled 396
Info:MAIN:Time 169, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.185] seq 49408, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 49664, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 51200, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 51456, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 51200, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 51456, flags 2049
Info:MQTT:MQTT deduper sent 61, culled 402
Info:MAIN:Time 170, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:GEN:dhcp=0 ip=192.168.1.109 gate=192.168.1.1 mask=255.255.255.0 mac=d8:1f:12:aa:1e:0b 
Info:DGR:DGR_Parse: [192.168.1.109] seq 51712, flags 1
Info:MQTT:Publishing val 0 to smartrul_bulb1/led_enableAll/get retain=1
Info:DGR:DGR_Parse: [192.168.1.109] seq 51968, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 51712, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 51968, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 52736, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 52992, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 52736, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 52992, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:MQTT:MQTT deduper sent 62, culled 408
Info:MAIN:Time 171, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 53248, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 53504, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 53760, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 53248, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 53504, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 53760, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 54272, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 54528, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 54784, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 55040, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 55296, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 55552, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 55808, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 56064, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 56320, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 56576, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 56832, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 57088, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 57344, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 54528, flags 2049
Info:MQTT:MQTT deduper sent 62, culled 424
Info:MAIN:Time 172, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 58112, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 58112, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 58368, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 58368, flags 2049
Info:DGR:DGR_Parse: [192.168.1.109] seq 58624, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 58624, flags 2049
Info:MQTT:MQTT deduper sent 62, culled 428
Info:MAIN:Time 173, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 61184, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 61440, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 61696, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 61184, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 61440, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 61696, flags 2049
Info:MQTT:MQTT deduper sent 62, culled 442
Info:MAIN:Time 175, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 61952, flags 1
Info:MQTT:Publishing val 0 to smartrul_bulb1/led_enableAll/get retain=1
Info:DGR:DGR_Parse: [192.168.1.109] seq 62208, flags 1
Info:DGR:DGR_Parse: [192.168.1.109] seq 62464, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 61952, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 62208, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 62464, flags 2049
Info:DGR:DGR_Parse: [192.168.1.185] seq 4352, flags 0
Info:DGR:DGR_Parse: [192.168.1.109] seq 64512, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 64512, flags 2049
Info:MQTT:MQTT deduper sent 63, culled 450
Info:MAIN:Time 178, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 65280, flags 1
Info:DGR:DGR_Parse: [192.168.1.185] seq 65280, flags 2049
Info:MQTT:MQTT deduper sent 63, culled 453
Info:MAIN:Time 179, free 83480, MQTT 1(1), bWifi 1, secondsWithNoPing -1, socks 4/38
Info:DGR:DGR_Parse: [192.168.1.109] seq 512, flags 2
Info:DGR:DGR_Parse: [192.168.1.185] seq 512, flags 2050
Info:CFG:####### Boot Count 23 #######
Warn:CFG:CFG_InitAndLoad: Correct config has been loaded with 20 changes count.
Info:MAIN:Using SSID [Suliana]
Info:MAIN:Using Pass [0122345318]
Info:MQTT:MQTT_RegisterCallback called for bT smartrul_bulb1/ subT smartrul_bulb1/+/set
Info:MQTT:MQTT_RegisterCallback called for bT cmnd/smartrul_bulb1/ subT cmnd/smartrul_bulb1/+
Error:CMD:lfs is absent
Info:GEN:PIN_SetupPins pins have been set up.
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 1, free 90160, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 2, free 90160, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 3, free 90160, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 4, free 90160, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 5, free 90160, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MAIN:ssid:Suliana key:0122345318
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 6, free 84128, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 7, free 84128, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 8, free 83816, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 9, free 83816, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 10, free 83816, MQTT 0(0), bWifi 0, secondsWithNoPing 0, socks 2/38
Info:GEN:dhcp=0 ip=0.0.0.0 gate=0.0.0.0 mask=0.0.0.0 mac=d8:1f:12:aa:1e:0b 
Info:MAIN:wl_status 3
Info:MAIN:Main_OnWiFiStatusChange - WIFI_STA_CONNECTING
Info:MAIN:wl_status 10
Info:MAIN:Main_OnWiFiStatusChange - WIFI_STA_CONNECTED
Info:MAIN:wl_status 11
Info:MAIN:Main_OnWiFiStatusChange - WIFI_STA_CONNECTED
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 11, free 84480, MQTT 0(0), bWifi 1, secondsWithNoPing 0, socks 2/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:NTP:Drv DGR is not running.
Info:DGR:DRV_DGR_CreateSocket_Receive: Socket created, waiting for packets
Info:DGR:DRV_DGR_CreateSocket_Send: socket created
Info:NTP:Started DGR.
Info:MAIN:Time 15, free 84032, MQTT 0(0), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 17, free 84032, MQTT 0(0), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 19, free 84032, MQTT 0(0), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 20, free 84032, MQTT 0(0), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:GEN:dhcp=0 ip=192.168.1.109 gate=192.168.1.1 mask=255.255.255.0 mac=d8:1f:12:aa:1e:0b 
Info:MQTT:Publishing val Smartrul_bulb1 to smartrul_bulb1/host retain=1
Info:MQTT:[g_bPublishAllStatesNow] item -13 result 0
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 24, free 83944, MQTT 1(1), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:MQTT:Publishing val Build on Oct 23 2022 06:52:52 version 1.14.48 to smartrul_bulb1/build retain=1
Info:MQTT:[g_bPublishAllStatesNow] item -12 result 0
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 27, free 83944, MQTT 1(1), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 31, free 83944, MQTT 1(1), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:MAIN:Boot complete time reached (30 seconds)
Info:CFG:####### Set Boot Complete #######
Info:MQTT:MQTT deduper sent 0, culled 0
Info:MAIN:Time 32, free 83944, MQTT 1(1), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:MQTT:Publishing val 100 to smartrul_bulb1/led_dimmer/get retain=1
Info:MQTT:[g_bPublishAllStatesNow] item -7 result 0
Info:MQTT:MQTT deduper sent 3, culled 0
Info:MAIN:Time 39, free 71816, MQTT 1(1), bWifi 1, secondsWithNoPing 0, socks 5/38
Info:MQTT:MQTT deduper sent 3, culled 0
Info:MAIN:Time 43, free 71816, MQTT 1(1), bWifi 1, secondsWithNoPing 0, socks 5/38
Info:MQTT:MQTT deduper sent 3, culled 0
Info:MAIN:Time 47, free 83512, MQTT 1(1), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:MQTT:MQTT deduper sent 3, culled 0
Info:MAIN:Time 50, free 81384, MQTT 1(1), bWifi 1, secondsWithNoPing 0, socks 4/38
Info:GEN:dhcp=0 ip=192.168.1.109 gate=192.168.1.1 mask=255.255.255.0 mac=d8:1f:12:aa:1e:0b 
Info:MQTT:Publishing val 81176 to smartrul_bulb1/freeheap retain=1
Info:MQTT:[g_bPublishAllStatesNow] item -2 result 0
```

**Comment by ferbulous** [comment] 2022-10-30 16:29
Hi, thanks for the fixes with latest version 1.14.91
Changing brightness, and colors are working fine
The flickering seems to be gone

I can’t seem to figure out why openbeken still crashes if mqtt payload is sent from homeassistant/mqtt client with device group enabled.
I might need to connect to tx2 pin to get some log output.

**Comment by btsimonh** [comment] 2022-11-04 08:10
@ferbulous - i'll close this one for now, as original issue is resolved.
Do ping if the MQTT crashes are not fixed by  .123

**Closed by btsimonh** 2022-11-04 08:10 UTC

**Comment by ferbulous** [comment] 2022-11-05 04:55
@btsimonh hi, unfortunately the MQTT crash occurs remains when i tested on .124

Any useful logs i could share or some other settings i need to enable in openbk to prevent this?

**Comment by btsimonh** [comment] 2022-11-05 12:08
yeah, serial logging would be good at the point of the crash - especially if you ran 'logdelay 50' beforehand (this add a 50ms delay after each call to log, so the log can get out before the crash!!!).

but first, can you capture the actual MQTT (topic and data) which causes the crash - we can then test that directly by sending from Node Red, and see if it can be reproduced.

**Comment by ferbulous** [comment] 2022-11-08 10:05
> but first, can you capture the actual MQTT (topic and data) which causes the crash - we can then test that directly by sending from Node Red, and see if it can be reproduced.

I tried mqttexplorer & nodered, and tested this on/off payload when it crashes openbk
Device: led bulb

`cmnd/gu10_openbk_2/led_enableAll`

I tried sending brightness/temperature but I probably didn't get it right.
However if I change the brightness/temperature/color from ha dashboard it does crash openbk as well

<img width="743" alt="image" src="https://user-images.githubusercontent.com/24526737/200529978-bc075db0-adb6-428c-8c02-8906acccf0b2.png">
