### ISSUE TITLE
[bug] flag 8 only works when 2 pwm channels set, fails when 5 set RGB(color temp)(white brightness)

### ISSUE THREAD

**Issue by heathfx** [openshwprojects/OpenBK7231T_App#560] opened 2022-12-24 04:53 UTC
**Describe the bug**
flag 8 only works when 2 PWM channels set, fails when 5 set RGB(color temp)(white brightness).

I have a 100w Cree CMA21-100W-AL-9ACK with RGB and W+Color Temp.

P7 (PWM1) controls the brightness of the white light.
P8 (PWM2) controls the color temperature, 100% duty cycle is full warm, 0% is full cool.

The RGB channels are controlled with 3 PWM channels (pretty typical).

**expectation**
The expectation is that when enabling flag 8 with 5 PWM channels, the behavior on the 3 RGB channels remains unchanged, while the 2 channels controlling white light, switch from controlling warm white on ch 5 and cool white on ch 4...
-to-
...controlling color temp on ch 4 and white light brightness on ch 5.
on channel 4: 100% duty cycle is full warm, 0% is full cool.

**reality**
Absolutely nothing changes when flag 8 is enabled when more than 2 PWM channels are present.

**Firmware:**
- Version 1.15.223
- Device? Cree CMA21-100W-AL-9ACK
- Chip/model: BK7231T (tuya WB8P)
- Device config? 5 PWM channels mapped, flag 8 enabled

**Comment by openshwprojects** [comment] 2022-12-24 08:34
I think you are correct, thank you for reporting, but that's not a bug. It was simply not implemented.
I can try doing that for you today, will you help with testing?

**Comment by heathfx** [comment] 2022-12-24 13:10
Thank!

I would be happy to test today. (Off work for Christmas holiday, good time to tinker.)

**Comment by openshwprojects** [comment] 2022-12-24 14:33
Ok I am waiting for your test resul;ts

**Comment by heathfx** [comment] 2022-12-24 17:57
I did an OTA update to 1.15.226 and the white light function now works as expected with flag 8 enabled, but when I choose an RGB color, channel 5 is left on causing the bulb to have both the RGB and white leds on simultaneously. In RGB mode, channel 5 should go to 0.

**Comment by openshwprojects** [comment] 2022-12-25 02:08
Thank you for testing.
I have added a fix, can you check now?

**Comment by heathfx** [comment] 2022-12-25 03:15
Works perfect now. Thanks!

Now time to solder some wires to the rest of my bulbs and flash them!

**Comment by heathfx** [comment] 2022-12-25 03:31
Well...almost. Channel 4 should always mirror the color temp slider (last setting). If you turn the bulb on and the color temp is anything other than 6500K it will flicker once at power on. When in rgb mode or turned off, ch 5 should go to 0 and ch 4 should remain at its previous setting (color temp).

Channel 4 needs to be set before applying power to the white LEDs (channel 5), otherwise you get a glitchy look to the power on (like a florescent lamp turning on).

**Comment by openshwprojects** [comment] 2022-12-25 09:34
There are multiple ways to fix that, but can you try that?
https://github.com/openshwprojects/OpenBK7231T_App/commit/96d70fdf95ab08ff25b941d757a8460b58844410

**Comment by heathfx** [comment] 2022-12-25 10:21
This latest build works perfectly!

Thanks a bunch for your help!

**Comment by openshwprojects** [comment] 2022-12-27 17:25
I think it's safe to close it now.

**Closed by openshwprojects** 2022-12-27 17:25 UTC
